/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CreateStudentRequestDto } from './models/create-student-request-dto';
export { ErrorDto } from './models/error-dto';
export { Int32ResponseDto } from './models/int-32-response-dto';
export { ProblemDetails } from './models/problem-details';
export { Student } from './models/student';
export { StudentIEnumerableResponseDto } from './models/student-i-enumerable-response-dto';
export { StudentViewModel } from './models/student-view-model';
export { StudentViewModelResponseDto } from './models/student-view-model-response-dto';
export { UpdateStudentRequestDto } from './models/update-student-request-dto';
