/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StudentIEnumerableResponseDto } from '../../models/student-i-enumerable-response-dto';

export interface ApiStudentGetAllStudentsGet$Json$Params {
}

export function apiStudentGetAllStudentsGet$Json(http: HttpClient, rootUrl: string, params?: ApiStudentGetAllStudentsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentIEnumerableResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiStudentGetAllStudentsGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StudentIEnumerableResponseDto>;
    })
  );
}

apiStudentGetAllStudentsGet$Json.PATH = '/api/Student/GetAllStudents';
