/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorDto } from '../models/error-dto';
export interface Int32ResponseDto {
  data?: number;
  errors?: Array<ErrorDto> | null;
  message?: string | null;
}
