/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorDto } from '../models/error-dto';
import { StudentViewModel } from '../models/student-view-model';
export interface StudentViewModelIEnumerableResponseDto {
  data?: Array<StudentViewModel> | null;
  errors?: Array<ErrorDto> | null;
  message?: string | null;
}
