/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StudentViewModel {
  genderId: number;
  genderName: string | null;
  id: number;
  lastName: string | null;
  name: string | null;
}
