/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Student {
  genderId?: number;
  id?: number;
  lastName?: string | null;
  name?: string | null;
}
