/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorDto } from '../models/error-dto';
import { Student } from '../models/student';
export interface StudentIEnumerableResponseDto {
  data?: Array<Student> | null;
  errors?: Array<ErrorDto> | null;
  message?: string | null;
}
